import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/PixelOutlaw/spigot-plugin-parent
     */
    const val bandsaw: String = "io.pixeloutlaw.spigot-commons:bandsaw:" +
            Versions.io_pixeloutlaw_spigot_commons

    /**
     * https://github.com/PixelOutlaw/spigot-plugin-parent
     */
    const val spigot_commons_bom: String = "io.pixeloutlaw.spigot-commons:spigot-commons-bom:" +
            Versions.io_pixeloutlaw_spigot_commons

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://github.com/square/moshi
     */
    const val moshi: String = "com.squareup.moshi:moshi:" + Versions.com_squareup_moshi

    /**
     * https://github.com/square/moshi
     */
    const val moshi_adapters: String = "com.squareup.moshi:moshi-adapters:" +
            Versions.com_squareup_moshi

    /**
     * https://github.com/square/moshi
     */
    const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:" +
            Versions.com_squareup_moshi

    const val com_diffplug_gradle_spotless_gradle_plugin: String =
            "com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:" +
            Versions.com_diffplug_gradle_spotless_gradle_plugin

    const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:" +
            Versions.io_gitlab_arturbosch_detekt_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    const val nebula_nebula_bintray_gradle_plugin: String =
            "nebula.nebula-bintray:nebula.nebula-bintray.gradle.plugin:" +
            Versions.nebula_nebula_bintray_gradle_plugin

    const val nebula_maven_publish_gradle_plugin: String =
            "nebula.maven-publish:nebula.maven-publish.gradle.plugin:" +
            Versions.nebula_maven_publish_gradle_plugin

    const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:" +
            Versions.org_jetbrains_dokka_gradle_plugin

    const val nebula_project_gradle_plugin: String =
            "nebula.project:nebula.project.gradle.plugin:" + Versions.nebula_project_gradle_plugin

    const val nebula_release_gradle_plugin: String =
            "nebula.release:nebula.release.gradle.plugin:" + Versions.nebula_release_gradle_plugin

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:" + Versions.junit_jupiter

    /**
     * https://github.com/mockito/mockito
     */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

    /**
     * https://github.com/zafarkhaja/jsemver
     */
    const val java_semver: String = "com.github.zafarkhaja:java-semver:" + Versions.java_semver

    const val spigot_api: String = "org.spigotmc:spigot-api:" + Versions.spigot_api

    /**
     * https://junit.org/junit5/
     */
    const val junit_bom: String = "org.junit:junit-bom:" + Versions.junit_bom

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * http://github.com/google/truth
     */
    const val truth: String = "com.google.truth:truth:" + Versions.truth

    /**
     * https://github.com/shyiko/klob
     */
    const val klob: String = "com.github.shyiko.klob:klob:" + Versions.klob
}
